spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/group_notice?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.weaver.generator.model

springdoc:
  group-configs:
    - group: 'code'
      paths-to-match: '/**'
      packages-to-scan: com.weaver.generator.controller

knife4j:
  enable: true
  setting:
    swagger-model-name: 代码生成器接口文档